package main

import (
	_ "alethic-ism-query-api/docs" // Swagger docs (autogenerated) but needs to be imported
	apiv1 "alethic-ism-query-api/pkg/api/v1"
	"embed"
	"fmt"
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
	"html/template"
	"net/http"
	"os"
)

//go:embed templates/*.html
var templateFS embed.FS

func main() {
	//dataAccess = data.InitializeNewDataAccessFromEnvDSN()

	gin.SetMode(gin.DebugMode)
	gin.DebugPrintRouteFunc = func(httpMethod, absolutePath, handlerName string, nuHandlers int) {
		fmt.Printf("ROUTE %s %s -> %s (%d handlers)\n", httpMethod, absolutePath, handlerName, nuHandlers)
	}

	r := gin.Default()
	r.Use(gin.Logger())   // Logs each request with details
	r.Use(gin.Recovery()) // Recover from panics and log the error
	r.SetHTMLTemplate(template.Must(template.New("").ParseFS(templateFS, "templates/*.html")))

	setupRoutesV1(r)

	// Swagger documentation route
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// ReDoc documentation route
	r.GET("/redoc/*any", RedocHandler())

	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}
	err := r.Run(":" + port)
	if err != nil {
		return
	}
}

// @title Alethic ISM - Data Query API
// @version 1.0
// @description This is a query api for Alethic ISM using a storage class: database
// @termsOfService http://swagger.io/terms/

// @contact.name
// @contact.url
// @contact.email

// @license.name Quantum Wake OU - Copyright 2024
// @license.url

// @host localhost:8081
// @BasePath /api
func setupRoutesV1(r *gin.Engine) {
	stateQueryHandler := apiv1.NewStateQueryHandler(apiv1.DSN)
	v1StateQuery := r.Group("/api/v1/state/query")
	{
		v1StateQuery.POST("/:id", stateQueryHandler.HandleQueryState)
	}

	v1Vault := r.Group("/api/v1/vault")
	{
		v1Vault.POST("", apiv1.HandleCreateVault)
		v1Vault.GET("/:id", apiv1.HandleFetchVault)
		v1Vault.DELETE("/:id", apiv1.HandleDeleteVault)
	}

	embHandler := apiv1.NewEmbeddingHandler(apiv1.DSN)
	v1Embedding := r.Group("/api/v1/nlp/embeddings")
	{
		v1Embedding.POST("", embHandler.HandleUpsert)
		v1Embedding.POST("/batch", embHandler.HandleUpsertBatch)
		v1Embedding.GET("/:id", embHandler.HandleFindByID)
		v1Embedding.GET("/parent/:id", embHandler.HandleFindByParentID)
		v1Embedding.DELETE("/:id", embHandler.HandleDelete)
		v1Embedding.DELETE("/parent/:id", embHandler.HandleDeleteByParentID)
		v1Embedding.POST("/search", embHandler.HandleSearch)
		v1Embedding.POST("/migrate", embHandler.HandleMigrate)
	}
}

// RedocHandler serves ReDoc UI
func RedocHandler() gin.HandlerFunc {
	return func(c *gin.Context) {
		c.HTML(http.StatusOK, "redoc.html", gin.H{
			"SpecURL": "/api/v1/query/swagger/doc.json",
		})
	}
}
