basePath: /api/v1
definitions:
  dsl.Filter:
    properties:
      column:
        example: input
        type: string
      operator:
        allOf:
        - $ref: '#/definitions/dsl.Operator'
        example: =
      value:
        example: xyz
        type: string
    type: object
  dsl.FilterGroup:
    properties:
      filters:
        items:
          $ref: '#/definitions/dsl.Filter'
        type: array
      group_logic:
        description: '"AND" or "OR"'
        example: AND
        type: string
    type: object
  dsl.Operator:
    enum:
    - =
    - like
    - '!='
    - '>'
    - <
    type: string
    x-enum-varnames:
    - Equal
    - Like
    - NotEqual
    - GreaterThan
    - LessThan
  dsl.StateQuery:
    properties:
      filter_groups:
        items:
          $ref: '#/definitions/dsl.FilterGroup'
        type: array
      state_id:
        example: 465884e9-7a08-40d0-acff-148663a7c9cf
        type: string
      user_id:
        example: 77c17315-3013-5bb8-8c42-32c28618101f
        type: string
    type: object
  dsl.StateQueryResult:
    properties:
      column_name:
        type: string
      data_index:
        type: integer
      data_value:
        type: string
    type: object
  model.ErrorResponse:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample server.
  license:
    name: Quantum Wake OU - Copyright 2024
  termsOfService: http://swagger.io/terms/
  title: Alethic ISM - Data Query API
  version: "1.0"
paths:
  /query/state/{id}:
    post:
      consumes:
      - application/json
      description: Query state data with filters
      parameters:
      - description: State ID
        in: path
        name: id
        required: true
        type: string
      - description: the query groups and filters
        in: body
        name: dsl.StateQuery
        required: true
        schema:
          $ref: '#/definitions/dsl.StateQuery'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dsl.StateQueryResult'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      summary: Query state data
      tags:
      - State
swagger: "2.0"
